apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: devops-mlops
spec:
  selector:
    app: inference-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
